### ISSUE TITLE
Refactor Components to have a shared Super class

### ISSUE THREAD

**Issue by Zeustopher** [Lastrellik/Calico-Home-Security#17]
There is duplicated code in each of the components for the following:
- Pin Number
- Constructor setting a pin number
- Getting the pin number
- Storing a componentType String
- getting the componentType

This suggests we need a shared class that all of the current components can extend from.

Call the base class "Component".

**Comment by Lastrellik** [comment]
I've started on this. I just need to figure out the C++ syntax. The way you did the component classes is very foreign to me. @Zeustopher, do you have any resources on the format you were using, specifically the buzzer::buzzer() type of syntax?

**Comment by Lastrellik** [comment]
This should all be taken care of with my latest pull request.
