### ISSUE TITLE
Add detailed 'logging' statements

### ISSUE THREAD

**Issue by Zeustopher** [Lastrellik/Calico-Home-Security#28]
It would be nice to have detailed/comprehensive 'logging' statements which showed each step's start and end.

For example:
"Starting Component Testing"
"Testing LED........ PASS"
"Testing BUZZER....... PASS"
...
"Calibration Complete"
"Arming System"
"System Armed"
.......
"Line Tripped. Beginning Countdown..... 5.....4.....3.....2.....1...."
"Alarm Sounded"
.... etc etc etc etc

Since we don't really have a real 'log' file in the Arduino, this should all just be spit out on the Serial channel.

This should be configureable so that we can disable all 'log' statements. Perhaps make a variable called "debugging" and initially set it to true and then check that boolean's value before writing anything out to the log.

_(Future Idea: Perhaps could collect this output using a Raspberry Pi and actually persist it in a real log file?)_

**Comment by Zeustopher** [comment]
@Boomstick105 - This was the idea I had that I was talking to you about. Feel free to pick this one up and assign it to yourself and work on it if you'd like.

**Comment by Lastrellik** [comment]
The Serial.Print() commands seem to have somehow broken the code. I checked out the master branch and tried running it and it froze up in the middle of calibration. I tried for some time to try to fix it and couldn't get it to work. In [#39](https://github.com/Lastrellik/Calico-Home-Security/pull/39) I was resolved this by removing the various Serial.Print() commands throughout the code. 

Although I could have the PI ignore the various Serial messages, I feel like it would cause more headache than benefit. I plan on implementing a logging function in the PI that will use Java's logger API to store it to a text file on the PI. This can be easily done by using the SerialComm::sendLogMessage(String message) from the Arduino and the PI will log those messages automatically. However, raw Serial traffic messes with the PI currently.

Outside of the PI, what would we want to log to anyway?

**Comment by Zeustopher** [comment]
@Lastrellik - It looks like we were both working on fixing the issue at the same time. See my https://github.com/Lastrellik/Calico-Home-Security/pull/40 Just adding a tiny delay at the end of the method corrected the issue for me. Would you pull down that branch and see if it corrects it for you?

The downside of using the current SerialComm class is it seems to be _heavily_ designed towards communication with the PI. Serial debugging messages like these should be easily accessible to anyone by just hooking up the Serial Monitor in PlatformIO/Atom. I haven't (yet) gone through the entire class and used it yet so some of that statement of it being focused heavily towards PI communication is an assumption, but based on earlier commits I looked at and hearing you discuss the SHA1 stuff, it appears to be that way.

There is _huge_ value in logging statements scattered throughout code similar to what we have here. Then at a glance, when troubleshooting an issue, a person can hook up the unit via USB, launch the Serial Monitor, and see where the program is failing / what the sensor is reading / what is happening / etc.

What really should happen is these log statements should be wrapped with an if-check on the Properties::DEBUGGING_ACTIVE flag. If its on then it should go directly out to Serial. This is how I did it in my Wifi.cpp class.

So I'm of the opinion that, unless we can figure out how to do actual debugging with the Arduino and PlatformIO/Atom then we should keep the logging statements as-is-ish (with the refactor mentioned above to wrap them with the if check). OR, we could refactor the SerialComm class to somehow differentiate between this type of debug-logging and a log statement meant to be sent to the PI.

**Comment by Zeustopher** [comment]
We're going in a somewhat different direction on this. See https://github.com/Lastrellik/Calico-Home-Security/blob/master/docs/development/logging.md for details. I'm going to close this issue and we can reopen others in the future if needed.
