### ISSUE TITLE
Serial Commands for Nano

### ISSUE THREAD

**Issue by Boomstick105** [Lastrellik/Calico-Home-Security#32]
Serial Commands will be built in, to display the results of the current component transmitting information back to the Nano.

Looking to hard code it into the code of the libraries, looking ultimately to create a class where the commands are passed through instead to a library, to prevent redundancies of manually enter in the the serial lines within the code.

**Comment by Lastrellik** [comment]
I can do this one. I think this will be useful for many modules, so maybe we should make it part of the base.

Also, did you mean Uno instead of Nano?

**Comment by Zeustopher** [comment]
We're going in a somewhat different direction on this. See https://github.com/Lastrellik/Calico-Home-Security/blob/master/docs/development/logging.md for details. I'm going to close this issue and we can reopen others in the future if needed.
