### ISSUE TITLE
Documenting Code

### ISSUE THREAD

**Issue by Boomstick105** [Lastrellik/Calico-Home-Security#52]
It is clear to me I don't understand this code as well as I like to.

It is clear to me I don't know what a lot of the commands to and what purpose they do.

Since I'm trying to work on the serial.write commands, I thought it would be a good thing to pull comments in the code on what everything does, that way if someone comes in later they can see what things are being used for and why, without having to go through the base of the code to heavily themselves.

**Comment by Zeustopher** [comment]
@Boomstick105: Sorry - I hope I didn't discourage you on https://github.com/Lastrellik/Calico-Home-Security/pull/51 with all the comments. They seemed a little rushed and I just didn't want to get things into a 'bad' state for future devs looking at the code.

**Comment by Boomstick105** [comment]
It was really bad, after talking to Jason it's clear to me, I haven't found too much of place in this project. I look forward to working on good exampled, even it takes a good amount of learning.

**Comment by Zeustopher** [comment]
@Boomstick105 - This is probably done enough now to go ahead and close this issue.
