### ISSUE TITLE
Pi's SerialComm check for "matches("Arduino.*")" doesn't work on all platforms

### ISSUE THREAD

**Issue by Zeustopher** [Lastrellik/Calico-Home-Security#57]
I found that when I tried to run the Raspberry Pi app it would fail and give me the message `Arduino Uno Cannot Be Found` in the console. I found that this is happening in the `SerialComm` class of the Raspberry Pi app.

After debugging I found that this came down to how the comPort is being located. It is currently using ```.matches("Arduino.*")``` to locate the Arduino. However, on my machine (Windows 10) and with my board (Uno Rev. 2) it shows up as `USB Serial Device (COM3)`. It doesn't have the word `Arduino` in it anywhere.

I don't know the scope of this issue since I've only got one board and it is slightly older than some of the other boards (Rev. 3) that other group members have.

In order to correct the issue I had to add ```|| comPorts[i].getDescriptivePortName().matches("USB.*")``` to the if-check in order for it to pick up the board on my machine and have the app function properly.

The code causing this issue:
```java
private SerialPort getArduinoCommPort() {
  SerialPort[] comPorts = SerialPort.getCommPorts();
    for (int i = 0; i < comPorts.length; i++) {
      if (comPorts[i].getDescriptivePortName().matches("Arduino.*")) {
        return comPorts[i];
      }
    }
    throw new NoSuchElementException("Arduino Uno Cannot Be Found");
}
```

And with my modifications:
```java
private SerialPort getArduinoCommPort() {
  SerialPort[] comPorts = SerialPort.getCommPorts();
    for (int i = 0; i < comPorts.length; i++) {
      if (comPorts[i].getDescriptivePortName().matches("Arduino.*") || comPorts[i].getDescriptivePortName().matches("USB.*")) {
        return comPorts[i];
      }
    }
    throw new NoSuchElementException("Arduino Uno Cannot Be Found");
}
```

I didn't want to create a pull request for this without some discussion first because I don't know what the scope of the issue is. I'd like to see if @sithboy and @Boomstick105 can also run this java app and see what their boards show up like on their machines.

**Comment by sithboy** [comment]
At class right now. Will give it a go this afternoon.
-- 
Dave Tille

**Comment by Lastrellik** [comment]
@Zeustopher The only concern I have is that it's possible that other devices will start with USB. I wonder if we should make the regular expression a little more specific.

**Comment by Zeustopher** [comment]
Yeah - that would be fine with me. I had similar thoughts. I just don't know how best to expand the regex with only having two points of data. There could also be many other peripherals that match even a more specific one though since its description is _so_ vague.

Its possible that it is only my board too since I've got a little bit of an older one.

**Comment by Lastrellik** [comment]
On the same note, the only other USB device that plugs into the PI would maybe be a webcam or possibly an external hard drive. I'm not sure what it's descriptive port name would be. For development, however, who knows what devices are going to be plugged into the developer's computer. I initially had it set up so that the developer had to select which port was the arduino, but that's not exactly automatic.

**Comment by Lastrellik** [comment]
I think I got this to work with [#83](https://github.com/Lastrellik/Calico-Home-Security/pull/83), but it's a gamble if there are more than one serial devices plugged into the computer at once.
