### ISSUE TITLE
Do we need this file?

### ISSUE THREAD

**Issue by Lastrellik** [Lastrellik/Calico-Home-Security#64]
I thought the gitignore file  intentionally excluded [this file](https://github.com/Lastrellik/Calico-Home-Security/blob/master/platformio.ini). Was this pushed by mistake or is it intentionally in the repo?

**Comment by Zeustopher** [comment]
This is intentionally in the repo. This is the platformio "project definition". It is what tells platformio what dependencies in needs to pull in based on what board we are using. I've also hooked into it for brining in the wifi dependency. So yes - we need it.

**Comment by Lastrellik** [comment]
@Zeustopher roger that.

**Comment by Zeustopher** [comment]
If you're interested in reading more, here is the docs about it: http://docs.platformio.org/en/latest/projectconf.html
