### ISSUE TITLE
Arduino Constantly Outputs to Serial

### ISSUE THREAD

**Issue by Lastrellik** [Lastrellik/Calico-Home-Security#68]
After creating my testing methods in the PI code I found that it started to behave weirdly... It kept trying to create a DataPacket and I thought that the Arduino wasn't supposed to be sending anything over Serial.

I Ran the Arduino code and looked at the Serial Monitor from within Platform.io and found that it sends data over the serial port even when the debugging and Raspberry Pi properties are set to false. This is due to missing (if Properties::MODULE_PI) checks before the serial write. It just floods the serial port with "-" symbols. For example: 
````c++
void Alarm::alertFailedAction(){
  Serial.write(13102); // 13102 = Log, Debug, Alarm failed action
  _buzzer->soundNegativeTone();
  _redLED->flash(1000);
}
````
The above code should be turned into this:
````c++
void Alarm::alertFailedAction(){
  if(Properties::MODULE_PI) Serial.write(13102); // 13102 = Log, Debug, Alarm failed action
  _buzzer->soundNegativeTone();
  _redLED->flash(1000);
}
````
or this:
````c++
void Alarm::alertFailedAction(){
  if(Properties::DEBUGGING_ACTIVE) Serial.write(13102); // 13102 = Log, Debug, Alarm failed action
  _buzzer->soundNegativeTone();
  _redLED->flash(1000);
````

@Zeustopher, should we do MODULE_PI or DEBUGGING_ACTIVE for writing the serial commands?

@Boomstick105 can you fix this one? I spent some time trying to find what the culprit is and I couldn't. Weirdly enough, the Raspberry Pi still worked, it wasn't until I modified the code to throw exceptions on illegal inputs that I noticed that it was constantly throwing illegal inputs. However, all logging functionality and what I'm trying to work on next will not work until this is fixed.

**Comment by Boomstick105** [comment]
Is it those few lines in particular throwing the errors, guess after
reading it i
I'm still a little loss, but I'm reading this after just barely waking up,
I can also clarify it later I  class with you.

**Comment by Boomstick105** [comment]
I see it after reading it a couple times, it just all looked very similar
reading it at first, I'll take a look at the code. Is this going you need a
full branch and pull request to change it or would I be able to submit the
changes from a past one?

**Comment by Zeustopher** [comment]
I'm on the fence on which it should be wrapped with (MODULE_PI or DEBUGGING_ACTIVE). I think for now lets do `if(Properties::MODULE_PI)`.

Really, every one of the Serial.write commands should have that if-check in front of it.

@Boomstick105 - You'll need to do the changes on a branch off master and then do a pull request.

**Comment by Lastrellik** [comment]
@Boomstick105 remember to checkout the master branch and then do a git pull before creating this second branch. It would also be helpful to load the code onto the Arduino and let it run with the Serial Monitor running. If MODULE_PI is set to false, nothing should print over serial.

**Comment by Lastrellik** [comment]
This has been resolved.
